### ISSUE TITLE
Add build statistics to `README`

### ISSUE THREAD

**Issue by avahoffman** [jhudsl/AnVIL_Book_Getting_Started#107]
The template has a nice chunk of code at the top that shows the build status. Add this to the top of the readme.

```
[![Render Bookdown and Coursera](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/actions/workflows/render-bookdown.yml/badge.svg)](https://github.com/jhudsl/DaSL_Course_Template_Bookdown/actions/workflows/render-bookdown.yml)
```

![image](https://user-images.githubusercontent.com/15618412/140364879-3610ea80-581b-423d-a19f-3547ec726b1c.png)

**Comment by chien-b1812825** [comment]
I think, I can do it

**Comment by avahoffman** [comment]
Decided this is not strictly necessary
