### ISSUE TITLE
Delete old .html files

### ISSUE THREAD

**Issue by KatherineCox** [jhudsl/AnVIL_Book_Getting_Started#108]
Old rendered files are hanging around and are available on the live site, e.g. https://jhudatascience.org/AnVIL_Book_Getting_Started/student-account-setup.html

I submitted an issue to the template repo jhudsl/DaSL_Course_Template_Bookdown#318 to solve the underlying problem, but we may want to manually clear out some old files in the meantime.

**Comment by avahoffman** [comment]
I had noticed this too.. Could definitely be a problem if folks are going to old links. Thanks for making the issue!

**Comment by KatherineCox** [comment]
Resolved by updates to the template github actions
